/*
 * sage_shell_entry.c
 * C shim: registers OS native callbacks into MetalVM, loads pre-compiled
 * sage_shell bytecode, and runs the SageLang shell.
 *
 * The bytecode arrays are generated by scripts/compile_sage_shell.sh and
 * placed in sage_shell_bytecode.h at build time.
 */

#include <stdint.h>
#include <stddef.h>
#include "metal_vm.h"
#include "console.h"
#include "keyboard.h"
#include "ramfs.h"
#include "fat32.h"
#include "power.h"
#include "status.h"
#include "timer.h"
#include "acpi.h"
#include "smp.h"
#include "battery.h"
#include "sysinfo.h"
#include "serial.h"
#include "pci.h"
#include "sdhci.h"
#include "shell.h"
#include "elf.h"
#include "version.h"
#include "dmesg.h"
#include "bootinfo.h"
#include "sage_shell_entry.h"

/* Generated at build time by scripts/compile_sage_shell.sh */
#include "sage_shell_bytecode.h"

#define SAGE_KEY_UP      1001
#define SAGE_KEY_DOWN    1002
#define SAGE_KEY_RIGHT   1003
#define SAGE_KEY_LEFT    1004
#define SAGE_KEY_HOME    1005
#define SAGE_KEY_END     1006
#define SAGE_KEY_DELETE  1008

static const char *SAGE_PROMPT = "root@sageos:/# ";

/* -----------------------------------------------------------------------
 * VM instance for the Sage shell (persistent across prompt cycles)
 * --------------------------------------------------------------------- */
static MetalVM g_sage_shell_vm;
static int     g_sage_shell_init = 0;
static int     g_sage_shell_running = 0;
static uint32_t g_input_start_row = 0;
static uint32_t g_input_start_col = 0;

/* -----------------------------------------------------------------------
 * I/O bridge
 * --------------------------------------------------------------------- */
static void bridge_write_char(char c) { console_putc(c); }

static int key_event_code(const KeyEvent *ev) {
    if (!ev || !ev->pressed) return -1;
    if (ev->extended) {
        switch (ev->scancode) {
        case 0x48: return SAGE_KEY_UP;
        case 0x50: return SAGE_KEY_DOWN;
        case 0x4D: return SAGE_KEY_RIGHT;
        case 0x4B: return SAGE_KEY_LEFT;
        case 0x47: return SAGE_KEY_HOME;
        case 0x4F: return SAGE_KEY_END;
        case 0x53: return SAGE_KEY_DELETE;
        default: return -1;
        }
    }
    if (ev->ascii) return (int)(unsigned char)ev->ascii;
    return -1;
}

static int bridge_read_char(void) {
    KeyEvent ev;
    for (;;) {
        if (!keyboard_wait_event(&ev)) return -1;
        if (ev.pressed && ev.ascii) return (int)(unsigned char)ev.ascii;
    }
}

/* -----------------------------------------------------------------------
 * Helper: get string arg safely
 * --------------------------------------------------------------------- */
static const char *arg_str(MetalVM *vm, MetalValue *args, int argc, int i) {
    if (i >= argc || args[i].type != MV_STR) return "";
    return metal_string_get(vm, args[i].as.str_idx);
}

static long long arg_num(MetalValue *args, int argc, int i) {
    if (i >= argc || args[i].type != MV_NUM) return 0;
    union { double d; uint64_t u; } v; v.u = args[i].as.num_bits;
    return (long long)v.d;
}

static MetalValue mv_str_lit(MetalVM *vm, const char *s) {
    int n = 0; while (s[n]) n++;
    return mv_str(vm, s, n);
}

static MetalValue mv_dbl(double d) {
    union { double d; uint64_t u; } v; v.d = d;
    return mv_num(v.u);
}

/* -----------------------------------------------------------------------
 * Native callback implementations
 * --------------------------------------------------------------------- */

/* --- Output --- */
static MetalValue n_write_char(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; console_putc((char)(int)arg_num(a,c,0)); return mv_nil();
}
static MetalValue n_write_str(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; console_write(arg_str(vm,a,c,0)); return mv_nil();
}

/* --- Input --- */
static MetalValue n_read_char(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; (void)a; (void)c;
    return mv_dbl((double)bridge_read_char());
}
static MetalValue n_read_key(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; (void)a; (void)c;
    KeyEvent ev;
    for (;;) {
        if (!keyboard_wait_event(&ev)) return mv_dbl(-1.0);
        int code = key_event_code(&ev);
        if (code >= 0) return mv_dbl((double)code);
    }
}
static MetalValue n_poll_char(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; (void)a; (void)c;
    KeyEvent ev;
    if (keyboard_poll_any_event(&ev) && ev.pressed && ev.ascii) {
        return mv_dbl((double)(unsigned char)ev.ascii);
    }
    return mv_dbl(-1.0);
}
static MetalValue n_poll_key(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; (void)a; (void)c;
    KeyEvent ev;
    if (!keyboard_poll_any_event(&ev)) return mv_dbl(-1.0);
    return mv_dbl((double)key_event_code(&ev));
}

/* --- Color --- */
static MetalValue n_set_color_hex(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; console_set_fg((uint32_t)arg_num(a,c,0)); return mv_nil();
}
static MetalValue n_get_color(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; (void)a; (void)c; return mv_dbl((double)console_get_fg());
}
static MetalValue n_set_color(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; console_set_fg((uint32_t)arg_num(a,c,0)); return mv_nil();
}

/* --- Console --- */
static MetalValue n_console_clear(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; (void)a; (void)c; console_clear(); return mv_nil();
}
static MetalValue n_cursor_home(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; (void)a; (void)c; console_set_cursor(0,0); return mv_nil();
}

static void serial_raw(const char *s) {
    while (*s) serial_putc(*s++);
}

static void serial_dec(uint32_t v) {
    char tmp[12];
    int n = 0;
    if (v == 0) {
        serial_putc('0');
        return;
    }
    while (v && n < (int)sizeof(tmp)) {
        tmp[n++] = (char)('0' + (v % 10));
        v /= 10;
    }
    while (n > 0) serial_putc(tmp[--n]);
}

static int c_strlen(const char *s) {
    int n = 0;
    while (s && s[n]) n++;
    return n;
}

static int c_starts_with(const char *text, const char *prefix) {
    if (!text || !prefix) return 0;
    while (*prefix) {
        if (*text != *prefix) return 0;
        text++;
        prefix++;
    }
    return 1;
}

static void serial_prompt_line(const char *line, int pos, const char *hint) {
    serial_putc('\r');
    serial_raw("\033[0K");
    serial_raw(SAGE_PROMPT);
    serial_raw(line);
    if (hint && *hint && c_starts_with(hint, line)) {
        serial_raw("\033[90m");
        serial_raw(hint + c_strlen(line));
        serial_raw("\033[0m");
    }
    serial_putc('\r');
    serial_raw("\033[");
    serial_dec((uint32_t)(c_strlen(SAGE_PROMPT) + pos + 1));
    serial_putc('G');
}

static MetalValue n_input_begin(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; (void)a; (void)c;
    console_get_cursor(&g_input_start_row, &g_input_start_col);
    return mv_nil();
}

static MetalValue n_line_redraw(MetalVM *vm, MetalValue *a, int c) {
    const char *line = arg_str(vm, a, c, 0);
    int pos = (int)arg_num(a, c, 1);
    int erase_len = (int)arg_num(a, c, 2);
    const char *hint = arg_str(vm, a, c, 3);
    int line_len = c_strlen(line);
    int hint_len = (hint && *hint && c_starts_with(hint, line)) ? c_strlen(hint) : 0;
    int visible_len = hint_len > line_len ? hint_len : line_len;
    if (pos < 0) pos = 0;
    if (pos > line_len) pos = line_len;

    int saved_serial_echo = console_get_serial_echo();
    console_set_serial_echo(0);

    console_set_cursor(g_input_start_row, g_input_start_col);
    console_write(line);

    if (hint_len > line_len) {
        uint32_t old = console_get_fg();
        console_set_fg(0x606060);
        console_write(hint + line_len);
        console_set_fg(old);
    }

    if (erase_len > visible_len) {
        for (int i = 0; i < erase_len - visible_len; i++) console_putc(' ');
    }

    uint32_t off = g_input_start_col + (uint32_t)pos;
    console_set_cursor(g_input_start_row + off / console_cols(), off % console_cols());

    console_set_serial_echo(saved_serial_echo);
    serial_prompt_line(line, pos, hint);
    return mv_nil();
}

/* --- String utilities exposed to Sage --- */
static MetalValue n_strlen(MetalVM *vm, MetalValue *a, int c) {
    const char *s = arg_str(vm,a,c,0);
    int n = 0; while (s[n]) n++;
    return mv_dbl((double)n);
}
static MetalValue n_streq(MetalVM *vm, MetalValue *a, int c) {
    const char *x = arg_str(vm,a,c,0), *y = arg_str(vm,a,c,1);
    int i = 0;
    while (x[i] && y[i] && x[i]==y[i]) i++;
    return mv_bool(x[i]==0 && y[i]==0);
}
static MetalValue n_char_at(MetalVM *vm, MetalValue *a, int c) {
    const char *s = arg_str(vm,a,c,0);
    int idx = (int)arg_num(a,c,1);
    int n = 0; while (s[n]) n++;
    if (idx<0||idx>=n) return mv_dbl(-1.0);
    return mv_dbl((double)(unsigned char)s[idx]);
}
static MetalValue n_substr(MetalVM *vm, MetalValue *a, int c) {
    const char *s = arg_str(vm,a,c,0);
    int from = (int)arg_num(a,c,1);
    int to   = (int)arg_num(a,c,2);
    int n = 0; while (s[n]) n++;
    if (from<0) from=0; if (to>n) to=n; if (from>=to) return mv_str_lit(vm,"");
    return mv_str(vm, s+from, to-from);
}
static MetalValue n_str_chop(MetalVM *vm, MetalValue *a, int c) {
    const char *s = arg_str(vm,a,c,0);
    int n = 0; while (s[n]) n++;
    if (n==0) return mv_str_lit(vm,"");
    return mv_str(vm, s, n-1);
}
static MetalValue n_chr(MetalVM *vm, MetalValue *a, int c) {
    char buf[2]; buf[0]=(char)(int)arg_num(a,c,0); buf[1]=0;
    return mv_str(vm, buf, 1);
}
static MetalValue n_num_to_str(MetalVM *vm, MetalValue *a, int c) {
    long long n = arg_num(a,c,0);
    int idx; metal_num_to_str(vm, n, &idx);
    MetalValue v; v.type=MV_STR; v.as.str_idx=idx; return v;
}
static MetalValue n_array_push(MetalVM *vm, MetalValue *a, int c) {
    if (c<2||a[0].type!=MV_ARR) return mv_nil();
    metal_array_push(vm, a[0].as.arr_idx, a[1]); return mv_nil();
}
static MetalValue n_len(MetalVM *vm, MetalValue *a, int c) {
    if (!a || c < 1) return mv_dbl(0.0);
    if (a[0].type == MV_STR) {
        const char *s = arg_str(vm, a, 1, 0);
        int n = 0;
        while (s[n]) n++;
        return mv_dbl((double)n);
    }
    if (a[0].type == MV_ARR) {
        return mv_dbl((double)metal_array_len(vm, a[0].as.arr_idx));
    }
    if (a[0].type == MV_DICT) {
        int idx = a[0].as.dict_idx;
        int max = (int)(sizeof(vm->dicts) / sizeof(vm->dicts[0]));
        if (idx >= 0 && idx < max) return mv_dbl((double)vm->dicts[idx].count);
    }
    return mv_dbl(0.0);
}

/* --- Version / system info --- */
static MetalValue n_version_string(MetalVM *vm, MetalValue *a, int c) {
    (void)a;(void)c; return mv_str_lit(vm, SAGEOS_VERSION);
}
static MetalValue n_input_backend(MetalVM *vm, MetalValue *a, int c) {
    (void)a;(void)c; return mv_str_lit(vm, keyboard_backend());
}

/* --- Framebuffer info --- */
static MetalValue n_fb_available(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; return mv_dbl(console_has_fb()?1.0:0.0);
}

static void u64_to_hex(uint64_t v, char *out) {
    const char *h="0123456789ABCDEF";
    out[0]='0'; out[1]='x';
    for(int i=0;i<16;i++) out[2+i]=h[(v>>(60-4*i))&0xF];
    out[18]=0;
}

static MetalValue n_fb_base_str(MetalVM *vm, MetalValue *a, int c) {
    (void)a;(void)c;
    SageOSBootInfo *b = console_boot_info();
    if (!b) return mv_str_lit(vm,"0x0");
    char buf[20]; u64_to_hex(b->framebuffer_base, buf);
    return mv_str(vm,buf,18);
}
static MetalValue n_fb_width_str(MetalVM *vm, MetalValue *a, int c) {
    (void)a;(void)c;
    SageOSBootInfo *b = console_boot_info();
    int idx; metal_num_to_str(vm, b?b->width:0, &idx);
    MetalValue v; v.type=MV_STR; v.as.str_idx=idx; return v;
}
static MetalValue n_fb_height_str(MetalVM *vm, MetalValue *a, int c) {
    (void)a;(void)c;
    SageOSBootInfo *b = console_boot_info();
    int idx; metal_num_to_str(vm, b?b->height:0, &idx);
    MetalValue v; v.type=MV_STR; v.as.str_idx=idx; return v;
}
static MetalValue n_fb_pps_str(MetalVM *vm, MetalValue *a, int c) {
    (void)a;(void)c;
    SageOSBootInfo *b = console_boot_info();
    int idx; metal_num_to_str(vm, b?b->pixels_per_scanline:0, &idx);
    MetalValue v; v.type=MV_STR; v.as.str_idx=idx; return v;
}

/* --- Memory / battery / CPU --- */
static MetalValue n_ram_used_mb(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c;
    return mv_dbl((double)(ram_used_bytes()/1024/1024));
}
static MetalValue n_ram_total_mb(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c;
    return mv_dbl((double)(ram_total_bytes()/1024/1024));
}
static MetalValue n_ram_used_str(MetalVM *vm, MetalValue *a, int c) {
    (void)a;(void)c;
    long long mb = (long long)(ram_used_bytes()/1024/1024);
    int idx; metal_num_to_str(vm,mb,&idx);
    /* append " MB" */
    int sidx; metal_string_concat(vm, idx, metal_string_intern(vm," MB",3), &sidx);
    MetalValue v; v.type=MV_STR; v.as.str_idx=sidx; return v;
}
static MetalValue n_ram_total_str(MetalVM *vm, MetalValue *a, int c) {
    (void)a;(void)c;
    long long mb = (long long)(ram_total_bytes()/1024/1024);
    int idx; metal_num_to_str(vm,mb,&idx);
    int sidx; metal_string_concat(vm, idx, metal_string_intern(vm," MB",3), &sidx);
    MetalValue v; v.type=MV_STR; v.as.str_idx=sidx; return v;
}
static MetalValue n_cpu_percent(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; return mv_dbl((double)timer_cpu_percent());
}
static MetalValue n_battery_percent(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; return mv_dbl((double)battery_percent());
}
static MetalValue n_smp_cpu_count(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; return mv_dbl((double)smp_cpu_count());
}
static MetalValue n_uptime_str(MetalVM *vm, MetalValue *a, int c) {
    (void)a;(void)c;
    uint64_t secs = timer_seconds();
    char buf[32]; int i=0;
    if (secs/3600) {
        long long h=(long long)(secs/3600);
        int idx; metal_num_to_str(vm,h,&idx);
        const char *hs=metal_string_get(vm,idx);
        while(*hs) buf[i++]=*hs++;
        buf[i++]='h'; buf[i++]=' ';
    }
    if ((secs/60)%60) {
        long long m=(long long)((secs/60)%60);
        int idx; metal_num_to_str(vm,m,&idx);
        const char *ms=metal_string_get(vm,idx);
        while(*ms) buf[i++]=*ms++;
        buf[i++]='m'; buf[i++]=' ';
    }
    long long s=(long long)(secs%60);
    int idx; metal_num_to_str(vm,s,&idx);
    const char *ss=metal_string_get(vm,idx);
    while(*ss) buf[i++]=*ss++;
    buf[i++]='s'; buf[i]=0;
    return mv_str(vm,buf,i);
}

/* --- btop helpers --- */
static MetalValue n_draw_bar(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;
    long long val   = arg_num(a,c,0);
    long long maxv  = arg_num(a,c,1);
    long long width = arg_num(a,c,2);
    if (maxv==0) maxv=1;
    long long filled = (val*width)/maxv;
    if (filled>width) filled=width;
    for(long long i=0;i<width;i++) console_putc(i<filled?'#':' ');
    return mv_nil();
}
static MetalValue n_delay_ms(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; timer_delay_ms((uint32_t)arg_num(a,c,0)); return mv_nil();
}

/* --- Kernel commands --- */
static MetalValue n_path_exists(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    VfsStat st;
    return mv_bool(vfs_stat(path, &st) == 0);
}
static MetalValue n_ls(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    if (!*path) path = "/";
    vfs_ls(path);
    return mv_nil();
}

static MetalValue n_cat(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    if (!*path) { console_write("\nusage: cat <path>"); return mv_nil(); }
    char buf[513];
    uint64_t off = 0;
    int first = 1;
    while (1) {
        int n = vfs_read(path, off, buf, 512);
        if (n < 0) {
            if (first) { console_write("\ncat: "); console_write(path); console_write(": "); console_write(vfs_strerror(n)); }
            break;
        }
        if (n == 0) break;
        if (first) { console_write("\n"); first = 0; }
        buf[n] = 0;
        console_write(buf);
        off += (uint64_t)n;
    }
    return mv_nil();
}

static MetalValue n_mkdir(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    if (!*path) { console_write("\nusage: mkdir <path>"); return mv_nil(); }
    int r = vfs_mkdir(path);
    if (r < 0) { console_write("\nmkdir: "); console_write(vfs_strerror(r)); }
    return mv_nil();
}

static MetalValue n_touch(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    if (!*path) { console_write("\nusage: touch <path>"); return mv_nil(); }
    int r = vfs_create(path);
    if (r < 0 && r != VFS_EEXIST) { console_write("\ntouch: "); console_write(vfs_strerror(r)); }
    return mv_nil();
}

static MetalValue n_rm(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    if (!*path) { console_write("\nusage: rm <path>"); return mv_nil(); }
    int r = vfs_unlink(path);
    if (r < 0) { console_write("\nrm: "); console_write(vfs_strerror(r)); }
    return mv_nil();
}

static MetalValue n_rm_recursive(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    int recursive = (int)arg_num(a, c, 1);
    if (!*path) { console_write("\nusage: rm [-rf] <path>"); return mv_nil(); }
    int r;
    if (recursive) {
        r = vfs_rm_rf(path);
    } else {
        r = vfs_unlink(path);
    }
    if (r < 0) { console_write("\nrm: "); console_write(vfs_strerror(r)); }
    return mv_nil();
}

static MetalValue n_stat(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    if (!*path) { console_write("\nusage: stat <path>"); return mv_nil(); }
    VfsStat st;
    int r = vfs_stat(path, &st);
    if (r < 0) { console_write("\nstat: "); console_write(path); console_write(": "); console_write(vfs_strerror(r)); return mv_nil(); }
    console_write("\n  File: "); console_write(st.name);
    console_write("\n  Type: "); console_write(st.type == VFS_DIRECTORY ? "directory" : (st.type == VFS_SYMLINK ? "symlink" : "file"));
    console_write("\n  Size: "); console_u32((uint32_t)st.size); console_write(" B");
    return mv_nil();
}

static MetalValue n_write(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    const char *content = arg_str(vm, a, c, 1);
    if (!*path) { console_write("\nusage: write <path> <content>"); return mv_nil(); }
    vfs_create(path);
    int clen = 0; const char *p = content; while (*p) { clen++; p++; }
    int r = vfs_write(path, 0, content, (size_t)clen);
    if (r < 0) { console_write("\nwrite: "); console_write(vfs_strerror(r)); }
    return mv_nil();
}

static MetalValue n_execelf(MetalVM *vm, MetalValue *a, int c) {
    const char *path = arg_str(vm, a, c, 0);
    const char *fd; uint64_t sz = ramfs_find_size(path, &fd);
    if (!fd) { console_write("\nexecelf: no such file: "); console_write(path); return mv_nil(); }
    elf_exec(fd, sz); return mv_nil();
}
static int g_shell_exec_active = 0;
static MetalValue n_shell_exec(MetalVM *vm, MetalValue *a, int c) {
    if (g_shell_exec_active) {
        console_write("\n[debug] shell_exec reentrancy detected!\n");
        return mv_nil();
    }
    g_shell_exec_active = 1;
    shell_exec_command(arg_str(vm, a, c, 0));
    g_shell_exec_active = 0;
    return mv_nil();
}
static MetalValue n_shell_completion_count(MetalVM *vm, MetalValue *a, int c) {
    return mv_dbl((double)shell_completion_count(arg_str(vm, a, c, 0)));
}
static MetalValue n_shell_completion_at(MetalVM *vm, MetalValue *a, int c) {
    const char *s = shell_completion_at(arg_str(vm, a, c, 0), (int)arg_num(a, c, 1));
    return mv_str_lit(vm, s);
}
static MetalValue n_shell_completion_common(MetalVM *vm, MetalValue *a, int c) {
    const char *s = shell_completion_common_prefix(arg_str(vm, a, c, 0));
    return mv_str_lit(vm, s);
}
static MetalValue n_shell_suggestion(MetalVM *vm, MetalValue *a, int c) {
    const char *s = shell_suggestion(arg_str(vm, a, c, 0));
    return mv_str_lit(vm, s);
}
static MetalValue n_shell_print_completions(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;
    shell_print_completions(arg_str(vm, a, c, 0));
    return mv_nil();
}
static MetalValue n_keydebug(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; keyboard_keydebug(); return mv_nil();
}
static MetalValue n_dmesg_dump(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; dmesg_dump(); return mv_nil();
}
static MetalValue n_dmesg_get_total(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; return mv_dbl((double)dmesg_get_total());
}
static MetalValue n_dmesg_get_head(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; return mv_dbl((double)dmesg_get_head());
}
static MetalValue n_dmesg_get_size(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; return mv_dbl((double)dmesg_get_size());
}
static MetalValue n_dmesg_get_char(MetalVM *vm, MetalValue *a, int c) {
    (void)vm; return mv_dbl((double)(unsigned char)dmesg_get_char((uint32_t)arg_num(a,c,0)));
}
static MetalValue n_status_print(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; status_print(); return mv_nil();
}
static MetalValue n_status_refresh(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; status_refresh(); return mv_nil();
}
static MetalValue n_sysinfo(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; sysinfo_cmd(); return mv_nil();
}
static MetalValue n_timer_info(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; timer_cmd_info(); return mv_nil();
}
static MetalValue n_smp_info(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; smp_cmd_info(); return mv_nil();
}
static MetalValue n_smp_boot_aps(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; smp_boot_aps(); return mv_nil();
}
static MetalValue n_battery_info(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; battery_cmd_info(); return mv_nil();
}
static MetalValue n_pci_info(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; pci_cmd_info(); return mv_nil();
}
static MetalValue n_sdhci_info(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; sdhci_cmd_info(); return mv_nil();
}
static MetalValue n_acpi_summary(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; acpi_cmd_summary(); return mv_nil();
}
static MetalValue n_acpi_tables(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; acpi_cmd_tables(); return mv_nil();
}
static MetalValue n_acpi_fadt(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; acpi_cmd_fadt(); return mv_nil();
}
static MetalValue n_acpi_madt(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; acpi_cmd_madt(); return mv_nil();
}
static MetalValue n_acpi_lid(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; acpi_cmd_lid(); return mv_nil();
}
static MetalValue n_acpi_battery(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; acpi_cmd_battery(); return mv_nil();
}
static MetalValue n_shutdown(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; power_shutdown(); return mv_nil();
}
static MetalValue n_suspend(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; power_suspend(); return mv_nil();
}
static MetalValue n_halt(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; power_halt(); return mv_nil();
}
static MetalValue n_reboot(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; power_reboot(); return mv_nil();
}
static MetalValue n_qemu_exit(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;(void)a;(void)c; power_qemu_exit(); return mv_nil();
}
static MetalValue n_sage_exec(MetalVM *vm, MetalValue *a, int c) {
    (void)vm;
    extern void sage_run_file(const char *path);
    sage_run_file(arg_str(vm,a,c,0));
    return mv_nil();
}

/* -----------------------------------------------------------------------
 * Register all natives
 * --------------------------------------------------------------------- */
static void register_natives(MetalVM *vm) {
#define REG(name, fn) metal_vm_register_native(vm, name, fn)
    /* Output */
    REG("os_write_char",    n_write_char);
    REG("os_write_str",     n_write_str);
    /* Input */
    REG("os_read_char",     n_read_char);
    REG("os_read_key",      n_read_key);
    REG("os_poll_char",     n_poll_char);
    REG("os_poll_key",      n_poll_key);
    /* Color */
    REG("os_set_color_hex", n_set_color_hex);
    REG("os_set_color",     n_set_color);
    REG("os_get_color_debug", n_get_color);
    /* Console */
    REG("os_console_clear", n_console_clear);
    REG("os_cursor_home",   n_cursor_home);
    REG("os_input_begin",   n_input_begin);
    REG("os_line_redraw",   n_line_redraw);
    /* String utils */
    REG("len",              n_len);
    REG("os_strlen",        n_strlen);
    REG("os_streq",         n_streq);
    REG("os_char_at",       n_char_at);
    REG("os_substr",        n_substr);
    REG("os_str_chop",      n_str_chop);
    REG("os_chr",           n_chr);
    REG("os_num_to_str",    n_num_to_str);
    REG("os_array_push",    n_array_push);
    /* System info */
    REG("os_version_string",n_version_string);
    REG("os_input_backend", n_input_backend);
    REG("os_fb_available",  n_fb_available);
    REG("os_fb_base_str",   n_fb_base_str);
    REG("os_fb_width_str",  n_fb_width_str);
    REG("os_fb_height_str", n_fb_height_str);
    REG("os_fb_pps_str",    n_fb_pps_str);
    REG("os_ram_used_mb",   n_ram_used_mb);
    REG("os_ram_total_mb",  n_ram_total_mb);
    REG("os_ram_used_str",  n_ram_used_str);
    REG("os_ram_total_str", n_ram_total_str);
    REG("os_cpu_percent",   n_cpu_percent);
    REG("os_battery_percent",n_battery_percent);
    REG("os_smp_cpu_count", n_smp_cpu_count);
    REG("os_uptime_str",    n_uptime_str);
    /* btop helpers */
    REG("os_draw_bar",      n_draw_bar);
    REG("os_delay_ms",      n_delay_ms);
    /* Kernel commands */
    REG("os_path_exists",   n_path_exists);
    REG("os_ls",            n_ls);
    REG("os_cat",           n_cat);
    REG("os_mkdir",         n_mkdir);
    REG("os_touch",         n_touch);
    REG("os_rm",            n_rm);
    REG("os_rm_recursive",  n_rm_recursive);
    REG("os_stat",          n_stat);
    REG("os_write",         n_write);
    REG("os_execelf",       n_execelf);
    REG("os_shell_exec",    n_shell_exec);
    REG("os_shell_completion_count",  n_shell_completion_count);
    REG("os_shell_completion_at",     n_shell_completion_at);
    REG("os_shell_completion_common", n_shell_completion_common);
    REG("os_shell_suggestion",        n_shell_suggestion);
    REG("os_shell_print_completions", n_shell_print_completions);
    REG("os_keydebug",      n_keydebug);
    REG("os_dmesg_dump",    n_dmesg_dump);
    REG("os_dmesg_get_total", n_dmesg_get_total);
    REG("os_dmesg_get_head",  n_dmesg_get_head);
    REG("os_dmesg_get_size",  n_dmesg_get_size);
    REG("os_dmesg_get_char",  n_dmesg_get_char);
    REG("os_status_print",  n_status_print);
    REG("os_status_refresh",n_status_refresh);
    REG("os_sysinfo",       n_sysinfo);
    REG("os_timer_info",    n_timer_info);
    REG("os_smp_info",      n_smp_info);
    REG("os_smp_boot_aps",  n_smp_boot_aps);
    REG("os_battery_info",  n_battery_info);
    REG("os_pci_info",      n_pci_info);
    REG("os_sdhci_info",    n_sdhci_info);
    REG("os_acpi_summary",  n_acpi_summary);
    REG("os_acpi_tables",   n_acpi_tables);
    REG("os_acpi_fadt",     n_acpi_fadt);
    REG("os_acpi_madt",     n_acpi_madt);
    REG("os_acpi_lid",      n_acpi_lid);
    REG("os_acpi_battery",  n_acpi_battery);
    REG("os_shutdown",      n_shutdown);
    REG("os_suspend",       n_suspend);
    REG("os_halt",          n_halt);
    REG("os_reboot",        n_reboot);
    REG("os_qemu_exit",     n_qemu_exit);
    REG("os_sage_exec",     n_sage_exec);
#undef REG
}

/* --- System Init --- */
void sage_init_run(void) {
    extern void sage_run_file(const char *path);
    if (vfs_stat("/etc/init.sage", NULL) == 0) {
        sage_run_file("/etc/init.sage");
    } else {
        console_write("\nWARN: /etc/init.sage not found, skipping init system.\n");
    }
}

/* -----------------------------------------------------------------------
 * sage_shell_run — public entry point called from shell.c "sageshell" command
 * --------------------------------------------------------------------- */
void sage_shell_run(void) {
    if (g_sage_shell_running) {
        console_write("\nSageShell is already active.");
        return;
    }

    g_sage_shell_running = 1;

    if (!g_sage_shell_init) {
        metal_vm_init(&g_sage_shell_vm);
        g_sage_shell_vm.write_char = bridge_write_char;
        g_sage_shell_vm.read_char  = bridge_read_char;
        register_natives(&g_sage_shell_vm);
        g_sage_shell_init = 1;
    } else {
        /* Reset execution state but keep registered natives + string pool */
        g_sage_shell_vm.sp          = 0;
        g_sage_shell_vm.scope_depth = 0;
        g_sage_shell_vm.halted      = 0;
        g_sage_shell_vm.error       = 0;
        g_sage_shell_vm.error_msg   = 0;
        g_sage_shell_vm.heap_used    = 0;
    }

    /*
     * Load pre-compiled binary bytecode artifact (SGVM).
     * sage_shell_bytecode[] is generated by scripts/compile_sage_shell.sh
     * and embedded via sage_shell_bytecode.h at build time.
     */
    if (!metal_vm_load_binary(&g_sage_shell_vm,
                             sage_shell_bytecode,
                             (int)sage_shell_bytecode_len)) {
        console_write("\nsageshell: error loading bytecode artifact\n");
        g_sage_shell_running = 0;
        return;
    }

    int result = metal_vm_run(&g_sage_shell_vm);
    if (result < 0) {
        console_write("\nsageshell: runtime error: ");
        console_write(g_sage_shell_vm.error_msg
                      ? g_sage_shell_vm.error_msg : "unknown");
        console_write("\n");
    }

    g_sage_shell_running = 0;
}
